baseURL = "perfume6.netlify.app"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "Perfume Awards"
title = "Perfume Awards"
[markup.goldmark.renderer]
unsafe = true
