[de]
contentDir = "content/deutsch"
copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
languageName = "English"
title = "Bigspring Hugo"
weight = 2
[en]
contentDir = "content/deutsch"
copyright = "Copyright Perfume Awards 2021"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "The Awards"
footer_menu_middle = "Ceremony"
footer_menu_right = "Support"
languageName = "English"
title = "Perfume Awards"
weight = "2"
