[du]
contentDir = "content/deutsch"
copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
languageName = "English"
title = "Bigspring Hugo"
weight = 2
[en]
contentDir = "content/english"
copyright = "Perfume Awards 2021"
footer_content = "Síguenos en RRSS para estar al tanto de las últimas actualizaciones del mundo del perfume"
footer_menu_left = "Navegar"
footer_menu_middle = "Premios"
footer_menu_right = "Soporte"
languageName = "Español"
title = "Perfume Awards"
weight = 1
