[de]
contentDir = "content/deutsch"
copyright = "Copyright Perfume Awards 2021"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Awards"
footer_menu_middle = "Ceremony"
footer_menu_right = "Support"
languageName = "English"
title = "Perfume Awards"
weight = 2
[en]
contentDir = "content/deutsch"
copyright = "Copyright Perfume Awards 2021"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "The Awards"
footer_menu_middle = "Ceremony"
footer_menu_right = "Support"
languageName = "English"
title = "Perfume Awards"
weight = "2"
