footer_left = []
[[footer_middle]]
name = "Ceremonia"
url = "https://perfume6.netlify.app/blog/ceremonia/"
[[footer_middle]]
name = "El Jurado"
url = "https://perfume6.netlify.app/blog/jurado/"
[[footer_middle]]
name = "Organizadores"
url = "https://perfume6.netlify.app/blog/post-3/"
[[footer_right]]
name = "Política de Privacidad"
url = "privacy-policy"
[[footer_right]]
name = "Términos y condiciones"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Premio"
url = "https://perfume6.netlify.app/blog/premios/"
weight = 2
[[main]]
name = "Jurado"
url = "https://perfume6.netlify.app/faq"
weight = 3
[[main]]
name = "Edición 2021"
url = "https://perfume6.netlify.app/blog/ceremonia/"
weight = "5"
