[[footer_left]]
name = "Votar"
url = "contact"
[[footer_left]]
name = "Blog"
url = "blog"
[[footer_left]]
name = "Resultados"
url = "pricing"
[[footer_middle]]
name = "Ceremonia"
url = "https://perfume6.netlify.app/blog/ceremonia/"
[[footer_middle]]
name = "El Jurado"
url = "https://perfume6.netlify.app/blog/jurado/"
[[footer_middle]]
name = "Base de Datos"
url = "https://perfume6.netlify.app/blog/post-4/"
[[footer_right]]
name = "Política de Privacidad"
url = "privacy-policy"
[[footer_right]]
name = "Términos y condiciones"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Premio"
url = "https://perfume6.netlify.app/blog/premios/"
weight = 2
[[main]]
name = "Jurado"
url = "https://perfume6.netlify.app/blog/jurado/"
weight = 3
[[main]]
name = "Edición 2021"
url = "https://perfume6.netlify.app/blog/ceremonia/"
weight = "5"
