[[footer_left]]
name = "Votar"
url = "contact"
[[footer_left]]
name = "Blog"
url = "blog"
[[footer_left]]
name = "Resultados"
url = "pricing"
[[footer_middle]]
name = "Pricing"
url = "pricing"
[[footer_middle]]
name = "Platform"
url = "#"
[[footer_middle]]
name = "Features"
url = "#"
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"
[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Blog"
url = "blog"
weight = 2
[[main]]
name = "Resultados"
url = "pricing"
weight = 3
[[main]]
name = "Votar"
url = "contact"
weight = 4
[[main]]
name = "FAQ"
url = "faq"
weight = 5
